services:

  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "${PSQL_PORT}:5432"
    environment:
      - POSTGRES_USER=${PSQL_USER}
      - POSTGRES_PASSWORD=${PSQL_PASSWORD}
      - POSTGRES_DB=${PSQL_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
